name: Dispatchable Log
description: A workflow that logs a value passed as input and optionally logs it again.

on:
    workflow_dispatch:
        inputs:
            value_to_log:
                description: 'The value to log'
                required: true
                type: string
            log_twice:
                description: 'Whether to log the value twice'
                required: false
                type: boolean
                default: false
            useless_input:
                description: 'This input is completely useless'
                required: true
                type: choice
                options:
                    - 0815
                    - 4711
                    - 1234

jobs:
    log_value:
        runs-on: ubuntu-latest
        steps:
            - name: Log value
              run: echo "${{ inputs.value_to_log }}"
            - name: Log value again
              if: ${{ inputs.log_twice }}
              run: echo "${{ inputs.value_to_log }}"
