name: GitHub CLI

on:
  push:
    branches: ['*']
  #pull_request:
    #types:
    #- opened
    #branches:
    #- main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Check GitHub CLI Version
        run: gh version
      - run: gh pr comment ${{ github.event.number }} --body "Hello There"
