name: GitHub CLI

on:
  pull_request:
    types:
    - opened
    branches:
    - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment ${{ github.event.number }} --body "Hello There"
