name: GitHub CLI

on:
  push:
    branches: ['*']
  #pull_request:
    #types:
    #- opened
    #branches:
    #- main

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check GitHub CLI Version
        run: gh version
      - run: gh pr comment ${{ github.event.number }} --body "Hello There"
