# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 23
              uses: actions/setup-java@v4
              with:
                  java-version: 23
                  distribution: temurin
                  cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: Copy artifact
              run: cp target/*-jar-with-dependencies.jar app.jar
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app
                  path: app.jar

    test-artifact-download:
        needs: build
        runs-on: ubuntu-latest
        container:
            image: openjdk:23-slim
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: app
            - name: Run app
              run: java -jar app.jar

    test-reusable:
        needs: build
        uses: ./.github/workflows/reusable-log.yaml
        with:
            value_to_log: 'Test'

    test-custom:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: nkilders/custom-action@main
              with:
                  milliseconds: 4711

    release:
        needs: [test-artifact-download, test-reusable]
        uses: ./.github/workflows/reusable-log.yaml
        with:
            value_to_log: 'Release'
            log_twice: true
