name: Secrets

on:
    workflow_dispatch:
        inputs:
            secret_value:
                description: Secret Value
                required: true
                type: string

jobs:
    log_value:
        runs-on: ubuntu-latest
        steps:
            - name: Log secret from repository
              run: echo "SUPER_SPECIAL_SECRET=${{ secrets.SUPER_SPECIAL_SECRET }}"
