name: Secrets

on:
    workflow_dispatch:
        inputs:
            secret_value:
                description: Secret Value
                required: true
                type: string

jobs:
    log_value:
        runs-on: ubuntu-latest
        steps:
            - name: Log secret from repository
              run: echo "${{ secrets.SUPER_SPECIAL_SECRET }}"
            - name: Log secret from input
              run: echo "${{ github.event.inputs.secret_value }}"
            - name: Mask and log secret from input
              run: |
                  echo "::add-mask::${{ github.event.inputs.secret_value }}"
                  echo "${{ github.event.inputs.secret_value }}"
            - name: Log random secret
              run: |
                  secret=$((RANDOM))
                  echo "Secret before masking = $secret"
                  echo "::add-mask::$secret"
                  echo "Secret after masking = $secret"
